global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/core_services/**/*.dart
          - lib/general_api/**/*.dart
          - lib/database/**/*.dart
      json_serializable:
        generate_for:
          - lib/core_services/**/*.dart
          - lib/general_api/**/*.dart
          - lib/database/**/*.dart
      retrofit_generator:
        generate_for:
          - lib/general_api/**/*.dart
      envied_generator|envied:
        generate_for:
          - lib/env.*.dart