name: hoyomi
description: "The application for watch anime and read manga for Android, iOS, MacOS, Windows, Linux and Web."
publish_to: 'none'
version: 0.3.69+107

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3

dependencies:
  adaptive_theme: ^3.7.0
  analyzer: ^7.4.4
  animations: ^2.0.11
  app_links: ^6.4.0
  archive: ^4.0.2
  awesome_extensions: ^2.0.21
  background_downloader: ^9.2.1
  battery_plus: ^6.2.1
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  choice: ^2.3.2
  circular_seek_bar: ^1.1.1
  colorful_iconify_flutter: ^0.0.5
  contentsize_tabbarview: ^0.0.2
  crypto: ^3.0.6
  dashed_circular_progress_bar: ^0.0.6
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  dio_compatibility_layer: ^0.1.0
  drop_down_list: ^2.0.0
  dynamic_height_grid_view: ^0.0.4
  email_validator: ^3.0.0
  envied: ^1.1.1
  event_bus: ^2.0.1
  filesize: ^2.0.1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.6
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_fullscreen: ^1.1.0
  flutter_hls_parser: ^2.0.1
  flutter_inappwebview:
    git:
      url: https://github.com/tachibana-shin/flutter_inappwebview
      ref: master
      path: flutter_inappwebview
  flutter_qjs:
    git:
      url: https://github.com/tachibana-shin/flutter_qjs
  flutter_localizations:
    sdk: flutter
  flutter_package_installer: ^0.0.1
  flutter_rust_bridge: 2.10.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_volume_controller: ^1.3.3
  flutter_widget_from_html: ^0.16.0
  freezed_annotation: ^3.0.0
  fullscreen_window: ^1.1.0
  get: ^4.6.6
  getwidget: ^6.0.0
  go_router: ^15.1.2
  go_transitions: ^0.8.0
  google_sign_in: ^6.3.0
  google_sign_in_all_platforms: ^1.1.0
  html: ^0.15.5
  http_cache_file_store: ^2.0.1
  iconify_flutter: ^0.0.7
  intl: 0.19.0
  jk_fast_listview: ^0.8.1
  json_annotation: ^4.9.0
  kaeru: ^0.1.16
  markdown: ^7.3.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_windows_video: ^1.0.11
  mediaquery_sizer: ^1.1.1
  number_paginator: ^1.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  pointycastle: ^4.0.0
  pool: ^1.5.1
  provider: ^6.1.4
  responsive_grid: ^2.4.4
  responsive_grid_list: ^1.4.0
  retry: ^3.1.2
  rhttp_plus: ^0.11.7
  rust_lib_hoyomi:
    path: rust_builder
  screen_brightness: ^2.1.2
  scrollable_positioned_list: ^0.3.8
  sealed_languages: ^2.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  # shirne_dialog: ^4.8.3
  skeletonizer: ^1.4.2
  speech_to_text: ^7.0.0
  speech_to_text_google_dialog: ^0.0.6
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.32
  sqlite_async: ^0.11.4
  subtitle: ^0.1.0-beta.3
  text_field_validation: ^1.1.6
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.1
  very_good_infinite_list: ^0.9.0
  video_player: ^2.9.5
  video_player_media_kit: ^1.0.6
  wakelock_plus: ^1.2.10
  web: ^1.1.1
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/tachibana-shin/flutter_inappwebview
      ref: master
      path: flutter_inappwebview

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  prompts: ^2.0.0
  json_serializable: ^6.8.0
  freezed: ^3.0.6
  retrofit_generator: ^9.1.9
  swagger_parser: ^1.22.1
  envied_generator: ^1.1.1
  flutter_launcher_icons: ^0.14.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/ca/
      - assets/images/
