name: hoyomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.6+35

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  analyzer: ^5.13.0
  archive: ^4.0.2
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  colorful_iconify_flutter: ^0.0.5
  contentsize_tabbarview: ^0.0.2
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  drop_down_list: ^0.0.8
  dynamic_height_grid_view: ^0.0.4
  email_validator: ^2.1.17
  envied: ^1.1.1
  event_bus: ^2.0.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_fullscreen: ^1.1.0
  flutter_hls_parser: ^2.0.1
  flutter_inappwebview:
    git:
      url: https://github.com/tachibana-shin/flutter_inappwebview
      ref: master
      path: flutter_inappwebview
  flutter_localizations:
    sdk: flutter
  flutter_package_installer: ^0.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_volume_controller: ^1.3.3
  flutter_widget_from_html: ^0.15.3
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  go_router: ^14.6.0
  go_transitions: ^0.7.0
  google_sign_in: ^6.3.0
  google_sign_in_all_platforms: ^1.1.0
  html: ^0.15.5
  http: ^1.2.2
  iconify_flutter: ^0.0.7
  intl: any
  json_annotation: ^4.9.0
  kaeru: ^0.1.9
  markdown: ^7.3.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_windows_video: ^1.0.11
  mediaquery_sizer: ^1.1.1
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  provider: ^6.1.4
  rss_feed_parser: ^1.0.6
  screen_brightness: ^2.1.2
  scrollable_positioned_list: ^0.3.8
  sealed_languages: ^2.1.0
  share_plus: ^10.1.2
  shared_preferences: ^2.5.3
  # shirne_dialog: ^4.8.3
  skeletonizer: ^1.4.2
  speech_to_text: ^7.0.0
  speech_to_text_google_dialog: ^0.0.6
  subtitle: ^0.1.0-beta.3
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.1
  very_good_infinite_list: ^0.9.0
  video_player: ^2.9.5
  video_player_media_kit: ^1.0.6
  wakelock_plus: ^1.2.10
  webview_flutter: ^4.10.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  prompts: ^2.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: ^8.2.1
  swagger_parser: ^1.22.1
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/ca/
      - assets/images/
