name: honyomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  archive: ^4.0.2
  card_swiper: ^3.0.1
  contentsize_tabbarview: ^0.0.2
  crypto: ^3.0.6
  device_info_plus: ^11.2.0
  drop_down_list: ^0.0.8
  dynamic_height_grid_view: ^0.0.4
  event_bus: ^2.0.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_hls_parser: ^2.0.1
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_subtitle: ^0.0.5
  flutter_vector_icons: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  go_router: ^14.6.0
  go_transitions: ^0.7.0
  grouped_list: ^6.0.0
  html: ^0.15.5
  http: ^1.2.2
  hugeicons: ^0.0.7
  iconify_flutter: ^0.0.7
  infinite_scroll_pagination: ^4.1.0
  intl: any
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  marquee: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  play_video: ^0.0.1
  pointycastle: ^3.9.1
  pull_to_refresh_flutter3: ^2.0.2
  rss_feed_parser: ^1.0.6
  scrollable_positioned_list: ^0.3.8
  scrollview_observer: ^1.23.0
  sharara_video_player: ^1.0.14
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.2
  subtitle_wrapper_package:
    git:
      url: https://github.com/tachibana-shin/flutter_subtitle_wrapper
      ref: main
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/ca/
      - assets/images/