name: honyomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  card_swiper: ^3.0.1
  device_info_plus: ^11.2.0
  drift_flutter: ^0.2.1
  drop_down_list: ^0.0.8
  dynamic_height_grid_view: ^0.0.4
  event_bus: ^2.0.1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_spinkit: ^5.2.1
  flutter_vector_icons: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  go_router: ^14.6.0
  go_transitions: ^0.7.0
  grouped_list: ^6.0.0
  html: ^0.15.5
  http: ^1.2.2
  hugeicons: ^0.0.7
  iconify_flutter: ^0.0.7
  infinite_scroll_pagination: ^4.1.0
  interactive_slider: ^0.4.0
  intl: any
  marquee: ^2.3.0
  mobx: ^2.4.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path: ^1.9.0
  path_provider: ^2.1.5
  pull_to_refresh_flutter3: ^2.0.2
  rss_feed_parser: ^1.0.6
  scrollable_positioned_list: ^0.3.8
  scrollview_observer: ^1.23.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  objectbox_generator: ^4.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/ca/