name: honyomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_vector_icons: ^2.0.0
  go_router: ^14.6.0
  go_transitions: ^0.7.0
  html: ^0.15.5
  http: ^1.2.2
  infinite_scroll_pagination: ^4.1.0
  interactive_slider: ^0.4.0
  intl: any
  scrollable_positioned_list: ^0.3.8
  scrollview_observer: ^1.23.0
  share_plus: ^10.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
