name: hoyomi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.9+10

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  archive: ^4.0.2
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  contentsize_tabbarview: ^0.0.2
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  drop_down_list: ^0.0.8
  dynamic_height_grid_view: ^0.0.4
  event_bus: ^2.0.1
  expandable_page_view: ^1.0.17
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_hls_parser: ^2.0.1
  flutter_inappwebview:
    git:
      url: https://github.com/tachibana-shin/flutter_inappwebview
      ref: master
      path: flutter_inappwebview
  flutter_localizations:
    sdk: flutter
  flutter_package_installer: ^0.0.1
  flutter_spinkit: ^5.2.1
  flutter_subtitle: ^0.0.5
  flutter_vector_icons: ^2.0.0
  flutter_widget_from_html: ^0.15.3
  get: ^4.6.6
  go_router: ^14.6.0
  go_transitions: ^0.7.0
  grouped_list: ^6.0.0
  html: ^0.15.5
  http: ^1.2.2
  hugeicons: ^0.0.7
  iconify_flutter: ^0.0.7
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  markdown: ^7.3.0
  marquee: ^2.3.0
  mediaquery_sizer: ^1.1.1
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pointycastle: ^3.9.1
  rss_feed_parser: ^1.0.6
  scrollable_positioned_list: ^0.3.8
  scrollview_observer: ^1.23.0
  sharara_video_player: ^1.0.14
  share_plus: ^10.1.2
  shared_preferences: ^2.5.2
  signals: ^6.0.2
  skeletonizer: ^1.4.2
  subtitle: ^0.1.0-beta.3
  subtitle_wrapper_package:
    git:
      url: https://github.com/tachibana-shin/flutter_subtitle_wrapper
      ref: main
  url_launcher: ^6.3.1
  very_good_infinite_list: ^0.9.0
  video_player: ^2.9.2
  wakelock_plus: ^1.2.10
  webview_flutter: ^4.10.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  prompts: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
      - assets/ca/
      - assets/images/
