// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for linux - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv7QAcCXVP5VffYbB0PkZlPexHjM0QkCI',
    appId: '1:972743069461:web:3fe295ddcccad292e9631c',
    messagingSenderId: '972743069461',
    projectId: 'hoyomi-app',
    authDomain: 'hoyomi-app.firebaseapp.com',
    storageBucket: 'hoyomi-app.firebasestorage.app',
    measurementId: 'G-C5T0Y3HRQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvofod7wlqgS8_JgB8hJo1sv0H9Vcw0E',
    appId: '1:972743069461:android:6c3dec2b1b357742e9631c',
    messagingSenderId: '972743069461',
    projectId: 'hoyomi-app',
    storageBucket: 'hoyomi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdMMmjSQC7HjpsqEoiFeDO2hfn3BDpHA',
    appId: '1:972743069461:ios:8d399f441a2716f3e9631c',
    messagingSenderId: '972743069461',
    projectId: 'hoyomi-app',
    storageBucket: 'hoyomi-app.firebasestorage.app',
    androidClientId:
        '972743069461-enisv4fqjs6pbv26qnjs1r6qoj2k6abi.apps.googleusercontent.com',
    iosClientId:
        '972743069461-1oulppj3blpvvro8hl9pd6p8e8lgi1km.apps.googleusercontent.com',
    iosBundleId: 'git.shin.hoyomi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwdMMmjSQC7HjpsqEoiFeDO2hfn3BDpHA',
    appId: '1:972743069461:ios:8d399f441a2716f3e9631c',
    messagingSenderId: '972743069461',
    projectId: 'hoyomi-app',
    storageBucket: 'hoyomi-app.firebasestorage.app',
    androidClientId:
        '972743069461-enisv4fqjs6pbv26qnjs1r6qoj2k6abi.apps.googleusercontent.com',
    iosClientId:
        '972743069461-1oulppj3blpvvro8hl9pd6p8e8lgi1km.apps.googleusercontent.com',
    iosBundleId: 'git.shin.hoyomi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv7QAcCXVP5VffYbB0PkZlPexHjM0QkCI',
    appId: '1:972743069461:web:dead0dbc8436fe6fe9631c',
    messagingSenderId: '972743069461',
    projectId: 'hoyomi-app',
    authDomain: 'hoyomi-app.firebaseapp.com',
    storageBucket: 'hoyomi-app.firebasestorage.app',
    measurementId: 'G-E3EL4KSPEX',
  );
}
