// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<DecodedImage> decodeImageRgba({required List<int> imageData}) => RustLib
    .instance
    .api
    .crateApiImageDecodeImageRgbaDecodeImageRgba(imageData: imageData);

class DecodedImage {
  final Uint8List pixels;
  final int width;
  final int height;

  const DecodedImage({
    required this.pixels,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => pixels.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedImage &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          width == other.width &&
          height == other.height;
}
