// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `do_unscramble_image_rows`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<Uint8List> unscrambleImageRows({
  required List<int> imageData,
  required List<RowBlock> blocks,
  required bool autoTrim,
}) => RustLib.instance.api.crateApiImageUnscrambleImageRowsUnscrambleImageRows(
  imageData: imageData,
  blocks: blocks,
  autoTrim: autoTrim,
);

Uint8List unscrambleImageRowsSync({
  required List<int> imageData,
  required List<RowBlock> blocks,
  required bool autoTrim,
}) => RustLib.instance.api
    .crateApiImageUnscrambleImageRowsUnscrambleImageRowsSync(
      imageData: imageData,
      blocks: blocks,
      autoTrim: autoTrim,
    );

class RowBlock {
  final int dy;
  final int height;

  const RowBlock({required this.dy, required this.height});

  @override
  int get hashCode => dy.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowBlock &&
          runtimeType == other.runtimeType &&
          dy == other.dy &&
          height == other.height;
}
