// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `do_unscramble_image_columns`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<Uint8List> unscrambleImageColumns({
  required List<int> imageData,
  required List<ColumnBlock> blocks,
  required bool autoTrim,
}) => RustLib.instance.api
    .crateApiImageUnscrambleImageColumnsUnscrambleImageColumns(
      imageData: imageData,
      blocks: blocks,
      autoTrim: autoTrim,
    );

Uint8List unscrambleImageColumnsSync({
  required List<int> imageData,
  required List<ColumnBlock> blocks,
  required bool autoTrim,
}) => RustLib.instance.api
    .crateApiImageUnscrambleImageColumnsUnscrambleImageColumnsSync(
      imageData: imageData,
      blocks: blocks,
      autoTrim: autoTrim,
    );

class ColumnBlock {
  final int dx;
  final int width;

  const ColumnBlock({required this.dx, required this.width});

  @override
  int get hashCode => dx.hashCode ^ width.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnBlock &&
          runtimeType == other.runtimeType &&
          dx == other.dx &&
          width == other.width;
}
