name: hoyomi_bridge
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2

dependencies:
  dart_eval: ^0.7.10
  eval_annotation: ^0.7.1
  freezed_annotation: ^3.0.0
  html: ^0.15.6
  json_annotation: ^4.9.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
