name: Auto Format and Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.3

      - name: Touch file .env
        run: touch .env

      - name: Touch file .env.web
        run: touch .env.web
  
      - name: Dart format
        run: find . -name "*.dart" \
            ! -name "*.g.dart" \
            ! -name "*.freezed.dart" \
            ! -path "./lib/general_api/*" \
            ! -path "./.dart_tool/*" \
            -print0 | xargs -0 dart format

      - name: Dart fix
        run: dart fix --apply

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto format and fix code'