on:
  push:
  pull_request:

name: Web extension test

jobs:
  ext_test:
    name: Web extension test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - run: cd web-*/*/

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Test
        run: |
          bun i
          bun run test