on:
  push:
    tags:
      - "v*"

name: Test, Build and Release

jobs:
  build_apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.27.1

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: "build/app/outputs/flutter-apk/*.apk"

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          ## If no one connects after 5 minutes, shut down server.
          wait-timeout-minutes: 5

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@c3f61b2a3db543ceee83c759ac8e48419a1a2211
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: build/app/outputs/flutter-apk/*.apk
          body: ${{ steps.changelog.outputs.changelog }}
