name: Test, Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    name: Build APK & IPA and Create Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      # Setup Java for APK build
      - uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      # Setup Flutter SDK
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.27.1

      - run: flutter pub get

      # Build APK (Android)
      - name: Build Release APK
        run: |
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > android/app/keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
          flutter build apk --release --split-per-abi

      # Build IPA (iOS)
      - name: Build Release IPA
        run: |
          flutter build ios --release --no-codesign
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -qq -r -9 build/ios/iphoneos/app-iphoneos-release-unsigned.ipa Payload

      # Create release directly
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          fetch: false

      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      # Upload APK and IPA files for release
      - name: Release APK and IPA
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/ios/iphoneos/app-iphoneos-release-unsigned.ipa
          body: ${{ steps.changelog.outputs.changelog }}
