name: Test, Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    outputs:
      apk-path: ${{ steps.upload_apk.outputs.path }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.27.1

      - run: flutter pub get

      - name: Decode and save keystore file
        run: |
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties file
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - run: flutter build apk --release --split-per-abi

      - name: Move APK to workspace folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/build_apk
          mv build/app/outputs/flutter-apk/*.apk $GITHUB_WORKSPACE/build_apk/
        id: upload_apk

  build_ipa:
    name: Build Release IPA
    runs-on: macOS-latest
    outputs:
      ipa-path: ${{ steps.upload_ipa.outputs.path }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.27.1

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 app-iphoneos-release-unsigned.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Move IPA to workspace folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/build_ipa
          mv build/ios/iphoneos/*.ipa $GITHUB_WORKSPACE/build_ipa/
        id: upload_ipa

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build_apk, build_ipa]

    steps:
      - name: Download APK and IPA files
        run: |
          cp -r $GITHUB_WORKSPACE/build_apk/* ./apk/
          cp -r $GITHUB_WORKSPACE/build_ipa/* ./ipa/

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          wait-timeout-minutes: 5

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          fetch: false

      - name: Get the changelog
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            ./apk/*.apk
            ./ipa/*.ipa
          body: ${{ steps.changelog.outputs.changelog }}
