name: Build and Release for Windows (.exe with Inno Setup)

on:
  push:

jobs:
  build_windows:
    name: Build Windows Installer
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.29.3

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Flutter pub get
        run: flutter pub get

      - name: Create .env file
        shell: bash
        run: echo -e "${{ secrets.ENV_CONTENT }}" > .env

      - name: Create .env.web file
        shell: bash
        run: echo -e "${{ secrets.ENV_WEB_CONTENT }}" > .env.web

      - name: Build runner
        shell: bash
        run: sh build_bunner.sh

      - name: Build Windows release
        run: flutter build windows --release

      - name: Create Inno Setup script
        run: powershell .\build_win32.ps

      - name: Compile installer with Inno Setup
        run: iscc hoyomi_installer.iss

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          wait-timeout-minutes: 5

      - name: Upload .exe installer
        uses: actions/upload-artifact@v4
        with:
          name: hoyomi-windows-installer
          path: HoyomiInstaller.exe
